# Generated by Django 3.2.5 on 2021-10-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previewPhotos/'),
        ),
    ]
