# Generated by Django 3.2.5 on 2021-10-31 17:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211031_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prev_image',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
