# Generated by Django 3.2.5 on 2021-11-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='prev_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='post',
            name='serial_num',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
