# Generated by Django 3.2.5 on 2021-11-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Save to Drafts'), ('P', 'Publish')], help_text='Save to Drafts or Publish?', max_length=1, null=True),
        ),
    ]
