# Generated by Django 3.2.5 on 2021-11-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ogtype',
            field=models.CharField(blank=True, choices=[('BL', 'blog'), ('AR', 'article'), ('WS', 'website')], help_text='Select the og:type', max_length=2, null=True),
        ),
    ]
