# Generated by Django 3.2.5 on 2021-11-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_ogtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_twitterhandle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='prev_img_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='prev_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='site_twitterhandle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='twittercard',
            field=models.CharField(blank=True, choices=[('S', 'summary'), ('SL', 'summary_large_image')], help_text='Select twitter:card', max_length=2, null=True),
        ),
    ]
