# Generated by Django 3.2.5 on 2021-11-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20211113_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ogtype',
            field=models.CharField(blank=True, choices=[('blog', 'blog'), ('article', 'article'), ('website', 'website')], help_text='Select the og:type', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='twittercard',
            field=models.CharField(blank=True, choices=[('summary', 'summary'), ('summary_large_image', 'summary_large_image')], help_text='Select twitter:card', max_length=25, null=True),
        ),
    ]
